[package]
name = "vite-actix"
version = "0.1.0"
edition = "2021"
description = "A library for integrating vite dev server to actix web server."
repository = "https://github.com/Drew-Chase/vite-actix"
license-file = "LICENSE"
autoexamples = true

[dependencies]
actix-web = "4.9.0"
futures-util = "0.3.31"
log = { version = "0.4.25", optional = false }
awc = "3.5.1"
anyhow = "1.0.95"

